name: Auto Merge Dev to Master

on:
  push:
    branches:
      - master
jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Fetch all branches
        run: git fetch --all
      - name: Merge branches into master
        run: |
          BRANCHES=$(git branch -r | grep -v '\->' | grep -v 'master' | sed 's/origin\///')
          for branch in $BRANCHES; do
            CURRENT_BRANCH=$(git branch --show-current)
            if [ "$CURRENT_BRANCH" != "master" ]; then
              git checkout master
            fi
            git pull origin master
            if git merge --no-ff --allow-unrelated-histories origin/$branch -m "Merge branch '$branch' into master"; then
              echo "Merge successful for branch $branch. Deleting branch $branch..."
              git push origin --delete $branch
              git push origin master
            else
              echo "Merge conflict or error occurred for branch $branch. Skipping..."
              git merge --abort
            fi
          done
