name: Auto Merge Dev to Master

on:
  push:
    branches:
      - dev

jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge dev into master
        run: |
          git checkout master
          git pull origin master
          if git merge --no-ff --allow-unrelated-histories origin/dev -m "Merge branch dev into master"; then
            echo "Merge successful for branch dev. Deleting branch dev..."
            git push origin master
          else
            echo "Merge conflict or error occurred for branch dev. Skipping..."
            git merge --abort
          fi

