name: Auto Merge Dev to Master

on:
  push:
    branches:
      - dev

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev Branch
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Set up Git
        run: |
          git config --global user.name 'yahyasghayron'
          git config --global user.email 'yahya.sghayron123@gmail.com'

      - name: Merge Dev into Master
        run: |
          git checkout master
          git merge dev --no-ff

      - name: Push to Master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin master

