name: Auto Merge Dev to Master

on:
  push:
    branches:
      - dev

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev Branch
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge Dev into Master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git checkout master
          git merge dev --no-ff
          git push origin master

